name: Generate Contract TypeScript Code

on:
  issues:
    types: [opened, edited]

jobs:
  generate-code:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'make ')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ethereum-abi-types-generator
        run: npm install ethereum-abi-types-generator --save-dev

      - name: Parse issue for contract details and set environment variables
        run: |
          CONTRACT_DETAILS=$(echo ${{ github.event.issue.title }} | cut -d ' ' -f 2)
          echo "CONTRACT_NAME=$(echo $CONTRACT_DETAILS | cut -d '@' -f 1)" >> $GITHUB_ENV
          echo "CONTRACT_VERSION=$(echo $CONTRACT_DETAILS | cut -d '@' -f 2)" >> $GITHUB_ENV
          
      - name: Fetch ABI from API and Save
        run: |
          mkdir -p ${{ github.workspace }}/${CONTRACT_NAME}
          ABI_URL="https://poolzfinancedata.com/contracts?NameVersion=${CONTRACT_NAME}@${CONTRACT_VERSION}"
          ABI_JSON=$(curl -s $ABI_URL)
          ABI=$(echo $ABI_JSON | jq '.[0].ABI')
          echo $ABI > ${{ github.workspace }}/${CONTRACT_NAME}/${CONTRACT_NAME}.json
        shell: bash

      - name: Generate TypeScript types
        run: npx abi-types-generator ${{ github.workspace }}/${CONTRACT_NAME}/${CONTRACT_NAME}.json --output=${{ github.workspace }}/${CONTRACT_NAME}

      - name: Create new branch
        run: |
          BRANCH_NAME="added-${CONTRACT_NAME}"
          git checkout -b $BRANCH_NAME

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Added generated TypeScript types for ${CONTRACT_NAME}"
          git push origin "added-${CONTRACT_NAME}"

      - name: Create Pull Request
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          PR_URL=$(gh pr create --title "Add generated TypeScript types for ${{ env.CONTRACT_NAME }}" --body "This PR adds generated TypeScript types for contract ${{ env.CONTRACT_NAME }}. Closes #${ISSUE_NUMBER}" --base master --head "added-${{ env.CONTRACT_NAME }}")
          PR_NUMBER=$(echo $PR_URL | grep -oP '\d+$')
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ env.PR_NUMBER }}
          method: squash

      - name: Close Issue
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          gh issue close $ISSUE_NUMBER --comment "The changes have been merged and the issue is now closed."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
